resources:
  pipelines:
    - pipeline: Previous Pipeline Trigger companieshouse2
      source: companies_house/companies_house_pipeline_section2
      project: Data_Engineering
      trigger: true
variables:
- group: hgdata-pipeline-variables
- group: aws-credential-group

pool: 'Default'

steps:
- script: pip install -r requirements.txt
  displayName: install requirements
- script: python3 main_section3.py pipeline
  displayName: Execute the file

