trigger:
- master
variables:
- group: aws-access-credentials
- group: preprod-connection-group
- name: serviceToPush
  value: 'companies-house-pipeline-container' # change this dependent on what the ecr repo is to be called
pool:
  vmImage: 'ubuntu-latest'
jobs:
- job: ConfigureAWSCredentials
  steps:
    - # needs to be AWS_DEFAULT_REGION, AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
    - script: |
        sudo pip3 install setuptools
        sudo pip3 install --upgrade awscli
      displayName: Install dependencies
    - script: |
        mkdir .aws
        echo "[default]\naws_access_key_id=$(AWS_ACCESS_KEY_ID)\naws_secret_access_key=$(AWS_SECRET_ACCESS_KEY)" > ~/.aws/credentials
        aws configure set region $(AWS_DEFAULT_REGION)
        $(aws ecr get-login --no-include-email)
      displayName: Signing into AWS ECR
- job: BuildAndPushDockerimage
  dependsOn: ConfigureAWSCredentials
  steps:
    - checkout: self
    - script: |
        export AWS_DEFAULT_REGION=$(AWS_DEFAULT_REGION)
        export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
        export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
        export preprod-host=$(preprod-host)
        export preprod-admin-user=$(preprod-admin-user) 
        export preprod-admin-pass=$(preprod-admin-pass)
        export preprod-database=$(preprod-database)

      displayName: 'Adding environment variables for AWS'
    - task: Docker@2
      displayName: 'Building the pipeline-companies-house image'
      inputs:
        repository: $(serviceToPush)
        command: 'build'
        Dockerfile: './Dockerfile'
        # do we need a aws-region arg?
        arguments: |
          --build-arg AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
          --build-arg AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
          --build-arg AWS_DEFAULT_REGION=$(AWS_DEFAULT_REGION)
        buildContext: .
        tags: |
          latest
          $(Build.BuildId)
    - script: docker image ls
      displayName: 'Listing Docker containers for debug'
    - task: ECRPushImage@1
      displayName: 'Pushing $(serviceToPush):latest to ECR'
      inputs:
        sourceImageName: $(serviceToPush)
        repositoryName: $(serviceToPush)
