resources:
  pipelines:
    - pipeline: Previous Pipeline Trigger companieshouse2
      source: companies_house/companies_house_pipeline_section2
      project: Data_Engineering
      trigger: true
variables:
- group: hgdata-pipeline-variables
- group: aws-credential-group

pool:
  vmImage: 'ubuntu-22.04'

jobs:
  job: section3_run
  steps:
  - script: pip install -r requirements.txt
    displayName: install requirements
  - script: python3 main_section3.py pipeline
    displayName: Execute the file
  # don't think we need this DeleteFiles@1, as this section only performs sql queries and such, no files are made.
  - task: DeleteFiles@1
    displayName: 'File Cleanup - removing all .zip and .csv files'
    inputs:
      contents: |
        *.csv
        *.zip

