trigger:
- master
variables:
- group: aws-access-credentials
- group: preprod-connection-group
- name: serviceToPush
  value: 'companies-house-pipeline-container' # change this dependent on what the ecr repo is to be called
pool:
  vmImage: 'ubuntu-latest'
jobs:
- job: ConfigureAWSCredentials
  steps:
    - script: |
        sudo pip3 install setuptools
        sudo pip3 install --upgrade awscli
      displayName: Install dependencies
    - script: |
        mkdir .aws
        echo "[default]\naws_access_key_id=$(aws-access-key-id-data-services)\naws_secret_access_key=$(aws-secret-key-data-services)" > ~/.aws/credentials
        aws configure set region $(aws-region)
        $(aws ecr get-login --no-include-email)
      displayName: Signing into AWS ECR
- job: BuildAndPushDockerimage
  dependsOn: ConfigureAWSCredentials
  steps:
    - checkout: self
    - script: |
        export aws-access-key-id-data-services=$(aws-access-key-id-data-services) #
        export aws-secret-key=$(aws-secret-key-data-services)
        export aws-region=$(aws-region)
        export preprod-host=$(preprod-host)
        export preprod-admin-user=$(preprod-admin-user) 
        export preprod-admin-pass=$(preprod-admin-pass)
        export preprod-database=$(preprod-database)
      displayName: 'Adding environment variables for AWS'
    - task: Docker@2
      displayName: 'Building the pipeline-companies-house image'
      inputs:
        repository: $(serviceToPush)
        command: 'build'
        Dockerfile: './Dockerfile'
        # do we need a aws-region arg?
        arguments: |
          --build-arg aws-access-key-id=$(aws-access-key-id) 
          --build-arg aws-secret-key=$(aws-secret-key) 
          --build-arg aws-region=$(aws-region)
          --build-arg preprod-host=$(preprod-host) 
          --build-arg preprod-admin-user=$(preprod-admin-user) 
          --build-arg preprod-admin-pass=$(preprod-admin-pass) 
          --build-arg prepod-database=$(preprod-database)
        buildContext: .
        tags: |
          latest
          $(Build.BuildId)
    - script: docker image ls
      displayName: 'Listing Docker containers for debug'
    - task: ECRPushImage@1
      displayName: 'Pushing $(serviceToPush):latest to ECR'
      inputs:
        sourceImageName: $(serviceToPush)
        repositoryName: $(serviceToPush)
