dtype_dict = {
    'CompanyName': str,
    ' CompanyNumber': str,
    'RegAddress.CareOf': str,
    'RegAddress.POBox': str,
    'RegAddress.AddressLine1': str,
    ' RegAddress.AddressLine2': str,
    'RegAddress.PostTown': str,
    'RegAddress.County': str,
    'RegAddress.Country': str,
    'RegAddress.PostCode': str,
    'CompanyCategory': str,
    'CompanyStatus': str,
    'CountryOfOrigin': str,
    'DissolutionDate': str,
    'IncorporationDate': str,
    'Accounts.AccountRefDay': str,
    'Accounts.AccountRefMonth': str,
    'Accounts.NextDueDate': str,
    'Accounts.LastMadeUpDate': str,
    'Accounts.AccountCategory': str,
    'Returns.NextDueDate': str,
    'Returns.LastMadeUpDate': str,
    'Mortgages.NumMortCharges': str,
    'Mortgages.NumMortOutstanding': str,
    'Mortgages.NumMortPartSatisfied': str,
    'Mortgages.NumMortSatisfied': str,
    'SICCode.SicText_1': str,
    'SICCode.SicText_2': str,
    'SICCode.SicText_3': str,
    'SICCode.SicText_4': str,
    'LimitedPartnerships.NumGenPartners': str,
    'LimitedPartnerships.NumLimPartners': str,
    'URI': str,
    'PreviousName_1.CONDATE': str,
    ' PreviousName_1.CompanyName': str,
    ' PreviousName_2.CONDATE': str,
    ' PreviousName_2.CompanyName': str,
    'PreviousName_3.CONDATE': str,
    ' PreviousName_3.CompanyName': str,
    'PreviousName_4.CONDATE': str,
    ' PreviousName_4.CompanyName': str,
    'PreviousName_5.CONDATE': str,
    ' PreviousName_5.CompanyName': str,
    'PreviousName_6.CONDATE': str,
    ' PreviousName_6.CompanyName': str,
    'PreviousName_7.CONDATE': str,
    ' PreviousName_7.CompanyName': str,
    'PreviousName_8.CONDATE': str,
    ' PreviousName_8.CompanyName': str,
    'PreviousName_9.CONDATE': str,
    ' PreviousName_9.CompanyName': str,
    'PreviousName_10.CONDATE': str,
    ' PreviousName_10.CompanyName': str,
    'ConfStmtNextDueDate': str,
    ' ConfStmtLastMadeUpDate': str,
    'org_id': str,
    'fragment_name': str,

}
