schedules:
- cron: '0 1 1-10 * *'
  displayName: 1am on the first-tenth of the month
  branches:
    include:
    - master
  always: True
pr: none
trigger: none
variables:
- group: hgdata-pipeline-variables
pool: 'Default'

steps:
- script: pip install -r requirements.txt
  displayName: install requirements for datatransfer
- script:
    python3 post_inserts_organisation.py $(preprodhost) $(adminuser) $(adminpass) $(database)
  displayName: Execute the file
