schedules:
- cron: '0 1 * * *'
  displayName: 1am on the first-tenth of the month CHANGE FROM * TO 1-10
  branches:
    include:
    - master
  always: True
pr: none
trigger: none
variables:
- group: hgdata-pipeline-variables
pool: 'Default'

steps:
- script: pip install -r requirements.txt
  displayName: install requirements
- script:
    python3 main.py $(preprodhost) $(adminuser) $(adminpass) $(database)
  displayName: Execute the file
