schedules:
- cron: '0 1 11 * *'
  displayName: 1am on the eleventh of the month
  branches:
    include:
    - master
  always: True
pr: none
trigger: none
variables:
- group: hgdata-pipeline-variables
pool: 'Default'

steps:
- script: pip install -r requirements.txt
  displayName: install requirements
- script: |
    python3 post_insert_updates_address.py
    python3 post_insert_updates_sic.py
  displayName: Execute the file